apiVersion: apps/v1
kind: Deployment
metadata:
  name:  istory
  labels:
    app:  istory
spec:
  selector:
    matchLabels:
      app: istory
  replicas: 3
  template:
    metadata:
      labels:
        app:  istory
    spec:
      initContainers:
        - name: check-mysql-ready
          image: mysql:8.0
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: istory-db-secret
                  key: MYSQL_PASSWORD
          command: [ 'sh',
                     '-c',
                     'until mysqladmin ping -u cloudwave -p${MYSQL_PASSWORD} -h cloudladder.cpq62cq0yvqi.ap-northeast-2.rds.amazonaws.com; do echo waiting for database; sleep 2; done;' ]

      containers:
        - name:  istory
          image:  553823310165.dkr.ecr.ap-northeast-2.amazonaws.com/cloudladder-repo:5bd0e122603ea40e441b76fa707c13c1238c007d
          envFrom:
            - configMapRef:
                name: istory-app-config
          env:
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: istory-db-secret
                  key: MYSQL_PASSWORD
            - name: spring.datasource.username
              valueFrom:
                configMapKeyRef:
                  name: istory-db-config
                  key: MYSQL_USER
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 600Mi
          readinessProbe:
            httpGet:
              path: /actuator
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
            successThreshold: 2
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort:  3306
              name:  istory
      volumes:
        - name: application-config
          configMap:
            name: istory-app-config
      restartPolicy: Always